language: node_js
node_js:
- 13.2
cache: npm
deploy:
  provider: s3
  access_key_id: AKIAZIUCQ6FCHKXGRX4Y
  secret_access_key:
    secure: o+/vml/zFrkyrgm/f2TAS2OJkB1Rs4yF+hQVKQJKyKb1QjspD/tykKH6D16UE7r/x8qKTTf8/6CJ6oupvk4xXFt1pYoIxpaQ7mfWMz7f1dM9MisoUN7pFw1Ujlh6UJPBNM21jY0mOi9ORDY8rhOIE32w26MAU+RFF7Kp0m9XinNarYMwlrPvWi5LrsnzCj9PxRHihpnaWUbx71nljjb1UZn7M3H/HeucQWpGD02LQ9iNTv9/BnHro0dIKYkDqlZiitznRFI+wIg54xIn14j1+bSRHfDtfVL2EOAqKMCbZVm+3v84Bns5weFGVz6EhMlrc/7MI0wnF9TYHu5AVfle6gIiY2cTwAbEL3k9jgh/5waluOML0WvB9gbeK7li8rsFEHDA/W0WgHDA4E3TGvHzPYfKgmr9FK+ZdE4VkY1A9LOWI287gtuQPzs+yZqIHfDhlINHDHBd5bRzG/BfOzuSp2cTqokjXGofhaFreBrpwQIki7GH5+1SkqkYfoW+2AfasKQVEmfOJ93TgqwK2Z8jILJEa8sMpWTso8s/L7S/iuQAv6Gk9rWjnDqV8NgVbaWET+jxf7TmoDZFooBG0rHkv6znXUIqiObjVrBYv4n7HywWsj/VSPotGn5dQqwPsUk5CsvmQmLcOB/avwBjjiCcs1T42uVhtx4BHDa3h5SmKFU=
  bucket: lexisdev
  region: us-east-2
  local-dir: dist
  upload-dir: cedict
  acl: public_read_write
  on:
    repo: alpheios-project/cedict
    branch: cedict
